name: VanillaMaps
version: '1.1.0'
main: uk.co.webdent.VanillaMaps.VanillaMapsPlugin
description: A fun vanilla-style custom map drawing tool.
api-version: '1.21.11'

permissions:
  custommaps.use:
    description: Allows a player to use the custom map commands
    default: true
